module.exports = function getConfiguration () {
  const { TEST_GUESTLINE_SITE_ID, TEST_GUESTLINE_INTERFACE_ID, TEST_GUESTLINE_OPERATOR_CODE, TEST_GUESTLINE_PASSWORD } = process.env
  return [TEST_GUESTLINE_SITE_ID, TEST_GUESTLINE_INTERFACE_ID, TEST_GUESTLINE_OPERATOR_CODE, TEST_GUESTLINE_PASSWORD]
}
