const CONNECTIONS = new Map([
  [
    'CONNECTION_MAILCHIMP',
    require('./CONNECTION_MAILCHIMP')
  ],
  [
    'CONNECTION_DELIVERECT',
    require('./CONNECTION_DELIVERECT')
  ],
  [
    'CONNECTION_UNTAPPD',
    require('./CONNECTION_UNTAPPD')
  ],
  [
    'CONNECTION_LOYALVERSE',
    require('./CONNECTION_LOYALVERSE')
  ],
  [
    'CONNECTION_PLAY_IT_GREEN',
    require('./CONNECTION_PLAY_IT_GREEN')
  ],
  [
    'CONNECTION_ATREEMO',
    require('./CONNECTION_ATREEMO')
  ],
  [
    'CONNECTION_CALENDLY',
    require('./CONNECTION_CALENDLY')
  ],
  [
    'CONNECTION_DATAVERSE',
    require('./CONNECTION_DATAVERSE')
  ],
  [
    'CONNECTION_ELITE_DYNAMICS',
    require('./CONNECTION_ELITE_DYNAMICS')
  ],
  [
    'CONNECTION_API',
    require('./CONNECTION_API')
  ]
])

module.exports = CONNECTIONS
