const CONNECTIONS = new Map([
  [
    'CONNECTION_ELITE_DYNAMICS',
    require('./CONNECTION_ELITE_DYNAMICS')
  ],
  [
    'CONNECTION_DVLA',
    require('./CONNECTION_DVLA')
  ],
  [
    'CONNECTION_JUSTEAT',
    require('./CONNECTION_JUSTEAT')
  ],
  [
    'CONNECTION_BLUE_MESH',
    require('./CONNECTION_BLUE_MESH')
  ],
  [
    'CONNECTION_EML',
    require('./CONNECTION_EML')
  ],
  [
    'CONNECTION_PASSKIT',
    require('./CONNECTION_PASSKIT')
  ],
  [
    'CONNECTION_SUMUP',
    require('./CONNECTION_SUMUP')
  ],
  [
    'CONNECTION_TEVALIS',
    require('./CONNECTION_TEVALIS')
  ],
  [
    'CONNECTION_DOMCENTRAL',
    require('./CONNECTION_DOMCENTRAL')
  ],

  [
    'CONNECTION_MAILCHIMP',
    require('./CONNECTION_MAILCHIMP')
  ],
  [
    'CONNECTION_DELIVERECT',
    require('./CONNECTION_DELIVERECT')
  ],
  [
    'CONNECTION_GUESTLINE',
    require('./CONNECTION_GUESTLINE')
  ],
  [
    'CONNECTION_UNTAPPD',
    require('./CONNECTION_UNTAPPD')
  ],
  [
    'CONNECTION_LOYALVERSE',
    require('./CONNECTION_LOYALVERSE')
  ],
  [
    'CONNECTION_PLAY_IT_GREEN',
    require('./CONNECTION_PLAY_IT_GREEN')
  ],
  [
    'CONNECTION_WOOCOMMERCE',
    require('./CONNECTION_WOOCOMMERCE')
  ],
  [
    'CONNECTION_ATREEMO',
    require('./CONNECTION_ATREEMO')
  ],
  [
    'CONNECTION_CALENDLY',
    require('./CONNECTION_CALENDLY')
  ],
  [
    'CONNECTION_DATAVERSE',
    require('./CONNECTION_DATAVERSE')
  ],
  [
    'CONNECTION_RINGCENTRAL',
    require('./CONNECTION_RINGCENTRAL')
  ],
  [
    'CONNECTION_ZENDESK',
    require('./CONNECTION_ZENDESK')
  ],
  [
    'CONNECTION_API',
    require('./CONNECTION_API')
  ],
  [
    'CONNECTION_SENDGRID_INBOUND',
    require('./CONNECTION_SENDGRID_INBOUND')
  ]
])

module.exports = CONNECTIONS
